services:
  pep:
    image: oryd/oathkeeper:v0.40.7
    ports:
      - "6003:6003" # Proxy
    command: serve --config=/etc/config/oathkeeper/config.yaml
    volumes:
      - type: bind
        source: ./config/oathkeeper
        target: /etc/config/oathkeeper
    restart: on-failure

  
  mongo:
    image: mongo:4.4
    command: --nojournal

  context:
    image: milestone-context

  broker:
    image: fiware/orion-ld:1.6.0
    links:
      - mongo
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo
    healthcheck:
      test: curl --fail -s http://broker:1026/version || exit 1
      interval: 5s